In [1]:
import pandas as pd

telemetry_df = pd.read_csv(
    "../models/electric-vehicle-telemetry-dataset.csv"
)

print(telemetry_df.shape)
telemetry_df.head()

(24277, 27)

,id,COND,LAT,LON,ALT,AX,AY,AZ,GX,GY,...,CH,VOL,CUR,SPD,ODO,BRK,ACC,AUT,ECO,AIR
0,4033900000,4,-21.783031,46.599998,0.0,196,1138,1575,24,34,...,59.0,22,61,31,25975.4,0,30,139,0,2
1,4114000000,4,21.000000,0.000000,0.0,-106,813,2156,-10,12,...,52.5,23,3,90,25998.0,0,8,135,0,0
2,6009100000,6,21.066668,0.000000,0.0,-82,951,1823,50,6,...,99.0,6,2,34,26125.2,0,0,272,0,0
3,7014600000,7,21.799545,0.000000,0.0,130,1053,1815,-2,-8,...,84.5,378,3,0,26200.0,16,0,199,0,2
4,7133000000,7,-21.925083,0.000000,0.0,432,1242,1640,-30,-62,...,75.5,370,20,54,26227.2,0,16,170,0,2

In [2]:
telemetry_df.columns.tolist()

['id',
 'COND',
 'LAT',
 'LON',
 'ALT',
 'AX',
 'AY',
 'AZ',
 'GX',
 'GY',
 'GZ',
 'Y',
 'M',
 'D',
 'H',
 'MIN',
 'SEC',
 'CH',
 'VOL',
 'CUR',
 'SPD',
 'ODO',
 'BRK',
 'ACC',
 'AUT',
 'ECO',
 'AIR']

In [3]:
telemetry_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 24277 entries, 0 to 24276
Data columns (total 27 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      24277 non-null  int64
 1   COND    24277 non-null  int64
 2   LAT     24277 non-null  float64
 3   LON     24277 non-null  float64
 4   ALT     24277 non-null  float64
 5   AX      24277 non-null  int64
 6   AY      24277 non-null  int64
 7   AZ      24277 non-null  int64
 8   GX      24277 non-null  int64
 9   GY      24277 non-null  int64
 10  GZ      24277 non-null  int64
 11  Y       24277 non-null  int64
 12  M       24277 non-null  int64
 13  D       24277 non-null  int64
 14  H       24277 non-null  int64
 15  MIN     24277 non-null  int64
 16  SEC     24277 non-null  int64
 17  CH      24277 non-null  float64
 18  VOL     24277 non-null  int64
 19  CUR     24277 non-null  int64
 20  SPD     24277 non-null  int64
 21  ODO     24277 non-null  float64
 22  BRK     24277 non-null  int64
 23  ACC     24277 non-null  int64
 24  AUT     24277 non-null  int64
 25  ECO     24277 non-null  int64
 26  AIR     24277 non-null  int64
dtypes: float64(5), int64(22)
memory usage: 5.0 MB

In [4]:
telemetry_df[
    [
        "SPD",
        "ACC",
        "BRK",
        "ECO",
        "CUR",
        "VOL"
    ]
].describe()

,SPD,ACC,BRK,ECO,CUR,VOL
count,24277.000000,24277.000000,24277.000000,24277.000000,24277.000000,24277.000000
mean,56.635046,14.474688,1.237962,8.715410,28.087696,98.682745
std,31.890343,15.401479,3.964158,39.968314,54.683208,148.708580
min,0.000000,0.000000,0.000000,0.000000,-52.000000,0.000000
25%,31.000000,0.000000,0.000000,0.000000,-3.000000,7.000000
50%,57.000000,12.000000,0.000000,0.000000,8.000000,17.000000
75%,82.000000,24.000000,0.000000,0.000000,47.000000,318.000000
max,134.000000,94.000000,38.000000,192.000000,301.000000,381.000000

In [5]:
telemetry_df["POWER_W"] = (
    telemetry_df["VOL"] *
    telemetry_df["CUR"]
)

telemetry_df["POWER_KW"] = (
    telemetry_df["POWER_W"] / 1000
)

telemetry_df["POWER_KW"].describe()

count    24277.000000
mean         2.620175
std          9.660820
min        -18.309000
25%         -0.002000
50%          0.093000
75%          1.131000
max         90.565000
Name: POWER_KW, dtype: float64

In [6]:
avg_speed = telemetry_df["SPD"].mean()

high_speed_ratio = (
    telemetry_df["SPD"] > 100
).mean() * 100

avg_acc = telemetry_df["ACC"].mean()

hard_brake_ratio = (
    telemetry_df["BRK"] > 10
).mean() * 100

print("Average Speed:", avg_speed)
print("High Speed Ratio:", high_speed_ratio)
print("Average ACC:", avg_acc)
print("Hard Brake Ratio:", hard_brake_ratio)

Average Speed: 56.63504551633233
High Speed Ratio: 7.690406557647156
Average ACC: 14.47468797627384
Hard Brake Ratio: 4.716398237014459

In [7]:
driving_score = 100

driving_score -= high_speed_ratio * 2
driving_score -= hard_brake_ratio * 3
driving_score -= avg_acc * 0.5

driving_score = max(0, min(100, driving_score))

print("Driving Score:", round(driving_score, 2))

Driving Score: 63.23

In [8]:
if driving_score >= 80:
    style = "Eco"
elif driving_score >= 60:
    style = "Normal"
else:
    style = "Aggressive"

print(style)

Normal